### ISSUE TITLE
对于服务发现查询实例信息提供推空保护措施 

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris-java#118]
**What is the feature you want to add?**

**Why do you want to add this feature?**

**How to implement this feature?**

**Additional context**

**Comment by shichaoyuan** [comment]
看现在代码里有个文件缓存，这个兜底机制不行么？

**Comment by chuntaojun** [comment]
> 

文件缓存和推空保护不是一个概念，推空表示sdk收到来自server的返回的空实例列表请求，然后正常更新本身的缓存，那么文件缓存也会一并更新

**Comment by chuntaojun** [comment]
文件缓存可以认为是一种本地容灾的保护手段

**Comment by shichaoyuan** [comment]
那“推空保护”的场景是什么？ 如果控制面确定配置为空了，那么数据面是不是应该接受？

**Comment by chuntaojun** [comment]
> 那“推空保护”的场景是什么？ 如果控制面确定配置为空了，那么数据面是不是应该接受？

可以参考下这个文章：https://segmentfault.com/a/1190000041403778

**Comment by chuntaojun** [comment]
并且这个是一个开关，而不是默认行为，根据开关自动选择

**Comment by gongzhijian** [comment]
assigne me for java

**Comment by gongzhijian** [comment]
帮忙看下把，大佬们，有争议的地方改了下
