### ISSUE TITLE
服务治理监控支持通过拉模式接入prometheus

### ISSUE THREAD

**Issue by andrewshan** [polarismesh/polaris-java#151]
当前支持推模式接入pushgateway，再通过pushgateway接入prometheus，但是存在以下问题：
1. pushgateway的数据，在应用下线时不会自动更新
2. 需要额外维护一套pushgateway集群，增加了故障点。

希望北极星可以接入原生prometheus拉取模式，当前go sdk已经接入

**Comment by wallezhang** [comment]
I'll try this issue. Please assign to me.

**Comment by andrewshan** [comment]
hey, thanks for your comment, good advises for the task, my opinion is:
1. New moudle: stat-prometheus-http-server
====
Change the old module 'stat-prometheus' to 'stat-pushgateway', then add new module 'stat-prometheus'

2. Expose context path and let prometheus pull the data
===
Yes, the expose plugin configuration can make like that:
```
#描述: 设置 prometheus http-server 的监听IP
#类型:string
#默认使用SDK的绑定IP
host: 
#描述: 设置 prometheus http-server 的监听端口
#类型:int
#默认值: 28080
#如果设置为负数，则不会开启默认的http-server
如果设置为0，则随机选择一个可用端口进行启动 http-server
port: 28080
#描述: 设置 prometheus http-server 的拉取path
#类型:string
#默认值: /metric
path: /metric
```
3. ReuseStatInfoCollectorContainer defined in stat-common module
It's ok, we can reuse the common logic as it is

**Comment by wallezhang** [comment]
> hey, thanks for your comment, good advises for the task, my opinion is:
> 
> 1. New moudle: stat-prometheus-http-server
>    ====
>    Change the old module 'stat-prometheus' to 'stat-pushgateway', then add new module 'stat-prometheus'
> 2. Expose context path and let prometheus pull the data
>    ===
>    Yes, the expose plugin configuration can make like that:
> 
> ```
> #描述: 设置 prometheus http-server 的监听IP
> #类型:string
> #默认使用SDK的绑定IP
> host: 
> #描述: 设置 prometheus http-server 的监听端口
> #类型:int
> #默认值: 28080
> #如果设置为负数，则不会开启默认的http-server
> 如果设置为0，则随机选择一个可用端口进行启动 http-server
> port: 28080
> #描述: 设置 prometheus http-server 的拉取path
> #类型:string
> #默认值: /metric
> path: /metric
> ```
> 
> 3. ReuseStatInfoCollectorContainer defined in stat-common module
>    It's ok, we can reuse the common logic as it is

Should I change the artifact to `stat-pushgateway` when change the old module to `stat-pushgateway`? I think if we change the module name to `stat-pushgateway`, the plugin name also needs to be changed from `prometheus` to `prometheus-pushgateway`. But this will lead to a break changes.
