### ISSUE TITLE
关于「推空保护开关」的 应用场景 和 粒度 问题

### ISSUE THREAD

**Issue by saigu** [polarismesh/polaris-java#154]
## Q1：什么情况下需要关闭「推空保护开关」？
「推空保护」的主要场景在于，当注册中心故障或异常推送 provider 空列表时，consumer端不做更新，维持调用ip列表。

简单想了下，如果是 服务真的下线，开不开都是调用不到，那和注册中心异常两种场景下保持「推空保护」都没什么问题。

想了解下什么场景下需要关闭这个开关？

## Q2：为什么开关配置在consumer维度？
看了下读取的是consumer配置。

![image](https://user-images.githubusercontent.com/28881997/174766103-f3555f7a-db7e-4914-a4d0-472f89abad30.png)

这样如果想单独配置某个provider维度的 推空保护关闭 就做不到了。

是不是配置在provider角度更合适？

## Q3：推空保护 是否需要作用于其他配置？
除了服务发现需要推空保护外，其他服务治理配置、路由信息是否需要推空保护？

服务下线 和 推空保护 两个场景不冲突，但是 其他配置信息为空 和 推空保护 似乎有些冲突。

应该如何设计比较好？

**Comment by chuntaojun** [comment]
推空保护措施 -> 保不保护的结果是否幂等

**Comment by chuntaojun** [comment]
服务治理规则 -> 走北极星配置中心 -> 一套灰度规则 & 版本管理

**Comment by chuntaojun** [comment]
推空保护措施从consumer侧移动至provider侧
