### ISSUE TITLE
polaris-java-sdk subscribe the register/unregister event (北极星客户端能订阅服务实例上下线的通知)

### ISSUE THREAD

**Issue by lapple06** [polarismesh/polaris-java#155]
when the service instance register or unregister to the polaris registry , the polaris java sdk can subscribe the event ， and react to the events

**Comment by chuntaojun** [comment]
https://github.com/polarismesh/polaris-java/blob/main/polaris-examples/discovery-example/src/main/java/com/tencent/polaris/discovery/example/consumer/WatchServiceExample.java

can resolve you question ?
