### ISSUE TITLE
对插件配置的对象进行缓存

### ISSUE THREAD

**Issue by wallezhang** [polarismesh/polaris-java#168]
**What is the feature you want to add?**
在获取插件配置的时候，代码参考这里：com.tencent.polaris.factory.config.plugin.PluginConfigImpl#getPluginConfig
目前只对配置的属性值进行了缓存，每次都会通过mapper反序列化一个新的对象，是不是可以考虑把反序列化之后的对象缓存呢？

**Why do you want to add this feature?**

**How to implement this feature?**

**Additional context**

**Comment by andrewshan** [comment]
好的，感谢建议，我们优化下

**Comment by wallezhang** [comment]
> 好的，感谢建议，我们优化下

如果评估需要做的话，我可以优化一下

**Comment by wallezhang** [comment]
@andrewshan 有一个疑问，在`com.tencent.polaris.factory.config.plugin.PluginConfigImpl`类中的plugin字段，上面有一个`@JsonProperty`注解，这个是在哪里会使用到呢？没看到有地方会用Jackson对这个类做序列化或者反序列化
