### ISSUE TITLE
北极星1.9版本，日志未打印到指定目录

### ISSUE THREAD

**Issue by yawenchen** [polarismesh/polaris-java#238]
1、使用默认polaris-log4j2.xml，北极星日志打印到应用的日志文件
2、当修改polaris-log4j2.xml ， root的level=trace，可以将info日志打印到北极星指定目录
3、北极星1.7没有问题， 应用日志使用log4j2.xml配置

<Configuration status="WARN">
    <Appenders>
        <RollingFile name="POLARIS_LOG_FILE" fileName="${sys:polaris.log.home}/polaris.log"
                filePattern="${sys:polaris.log.home}/polaris.log.%d{yyyy-MM-dd}.%i">
            <PatternLayout>
                <Pattern>[%-5level][%date{yyyy-MM-dd HH:mm:ss.SSS}][%thread][%X{traceId}][%X{serviceId}][%X{tranSeq}][%logger{36}:%L][%msg]%n</Pattern>
            </PatternLayout>

            <Policies>
                <TimeBasedTriggeringPolicy/>
                <SizeBasedTriggeringPolicy size="${sys:polaris.log.file.size:-10MB}"/>
            </Policies>

            <DefaultRolloverStrategy max="${sys:polaris.log.retain.count:-7}"/>
        </RollingFile>
    </Appenders>

    <Loggers>
        <Logger name="com.tencent.polaris"
                level="${sys:polaris.log.level:-info}"
                additivity="false">
            <AppenderRef ref="POLARIS_LOG_FILE"/>
        </Logger>
        <Root level="INFO">
            <AppenderRef ref="POLARIS_LOG_FILE"/>
        </Root>
    </Loggers>
</Configuration>

**Comment by ShanyouYu-Sean** [comment]
@yawenchen 这边测试北极星日志是可以打印到指定目录下的，可以提供下你测试出bug时的代码配置么？
