### ISSUE TITLE
grpc ConnectionManager.postContextInit.setExtensions.SwitchServerTask.run.switchClient

### ISSUE THREAD

**Issue by xiaohongxiedaima** [polarismesh/polaris-java#24]
when grpc client plugin execute `postContextInit` method,  it start a task and do `switchClient` operator

can someone tell me the reason of do `switchClient` operator. THK!!!

**Comment by chuntaojun** [comment]
#描述: 连接空闲时间（以最后一次消息交互时间来算），长连接模式下，当连接空闲超过一定时间后，SDK会主动释放连接
    connectionIdleTimeout: 60s
    #描述: server节点的切换周期，为了使得server的压力能够均衡，SDK会定期切换目标服务端节点
