### ISSUE TITLE
写缓存失败时，希望调整日志等级

### ISSUE THREAD

**Issue by yaoxuwan** [polarismesh/polaris-java#249]
使用服务发现时，一台机器部署了多个服务
多个服务写一个缓存，导致频繁的写缓存失败，打印错误日志
但是写缓存失败并不会影响服务，希望调整日志等级为WARN

相关日志
[polaris-inmemory-2] fail to persist service ServiceEventKey{serviceKey=ServiceKey{namespace='xxx', service='xxx'}, eventType=INSTANCE} after retry 2

fail to write file /tmp/xxx#instance.yaml.tmpjava.io.IOException: fail to lock file /tmp/xxx#instance.yaml.tmp, ignore and retry later

**Comment by chuntaojun** [comment]
> 

服务部署到了同一个目录下吗？

**Comment by yaoxuwan** [comment]
不同服务的jar包是在同一个目录

**Comment by chuntaojun** [comment]
1、建议不同的服务jar有自己单独的服务目录
2、日志等级的调整我们看下
