### ISSUE TITLE
调用服务实例注册接口报错：server error 400202: not found resource

### ISSUE THREAD

**Issue by fanrenren** [polarismesh/polaris-java#25]
ERR-1006(SERVER_USER_ERROR), server error 400202: not found resource

如果服务不存在就会报这个错！
请问必须通过控制台页面创建好服务之后，才可以调用实例注册接口吗？

**Comment by li-xiao-shuang** [comment]
有人处理嘛？

**Comment by chuntaojun** [comment]
目前是的，需要在服务端先创建对应的服务才可以注册服务，关于这一块的逻辑，可以在这个issue一起讨论下：https://github.com/polarismesh/polaris/issues/136

**Comment by andrewshan** [comment]
当前已经支持自动创建服务，可以使用最新的https://github.com/polarismesh/polaris/releases/tag/v1.3.1试试@fanrenren
