### ISSUE TITLE
rebinder found 2

### ISSUE THREAD

**Issue by albert-get** [polarismesh/polaris-java#252]
**Describe the bug**
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of method refreshScopeHealthIndicator in org.springframework.cloud.autoconfigure.RefreshEndpointAutoConfiguration required a single bean, but 2 were found:
	- affectedConfigurationPropertiesRebinder: defined by method 'affectedConfigurationPropertiesRebinder' in class path resource [com/tencent/cloud/polaris/config/PolarisConfigAutoConfiguration.class]
	- configurationPropertiesRebinder: defined by method 'configurationPropertiesRebinder' in class path resource [org/springframework/cloud/autoconfigure/ConfigurationPropertiesRebinderAutoConfiguration.class]

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed

**To Reproduce**
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-dependencies</artifactId>
    <version>2021.0.3</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
<dependency>
    <groupId>com.tencent.cloud</groupId>
    <artifactId>spring-cloud-tencent-dependencies</artifactId>
    <version>1.8.1-2021.0.3</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>

**Expected behavior**
a single bean

**Comment by chuntaojun** [comment]
这个问题麻烦转到 Spring Cloud Tencent

**Comment by lepdou** [comment]
@albert-get 

这个应该正常情况下是不会出现的，不过处理一下 @Primary 的应该更好。我们下个版本优化一下。感谢建议
