### ISSUE TITLE
配置中心优先读取系统变量,导致值获取不到

### ISSUE THREAD

**Issue by Paul101432** [polarismesh/polaris-java#260]
**Describe the bug**
配置值被系统变量优先读取

**To Reproduce**
比如配置项为 user.name 会读取主机名 而不是配置的值 

**Expected behavior**
能读取正确的配置值

**Environment**
- Version: [v1.10.1]

**Comment by chuntaojun** [comment]
用的是 Spring Cloud Tencent ？

**Comment by Paul101432** [comment]
> 用的是 Spring Cloud Tencent ？

里面的代码逻辑就是这样子的  所以有点迷 

com.tencent.polaris.configuration.client.internal.ConfigPropertiesFile#getProperty

依赖为: 
       <dependency>
            <groupId>com.tencent.polaris</groupId>
            <artifactId>polaris-all</artifactId>
            <version>1.10.1</version>
        </dependency>

**Comment by Paul101432** [comment]
> > > 用的是 Spring Cloud Tencent ？
> > 
> > 
> > 里面的代码逻辑就是这样子的 所以有点迷
> > com.tencent.polaris.configuration.client.internal.ConfigPropertiesFile#getProperty
> > 依赖为: com.tencent.polaris polaris-all 1.10.1
> 
> 你是有使用 Spring Cloud Tencent 吗？还是你直接裸的使用 polaris-java 的相关接口，这个要先明确下

但使用 polaris-java 的接口  跟里面的com.tencent.polaris.configuration.example.ConfigYamlFileExample写法一样 yml文件我配置属性不一样而已 就是 user.name . 上面例子程序传参都直接main方法的 args . 学浅的我都不知道咋找

**Comment by chuntaojun** [comment]
我们把这个能力去掉下，SDK的配置 key 读取只从配置文件中获取

**Comment by andrewshan** [comment]
> 我们把这个能力去掉下，SDK的配置 key 读取只从配置文件中获取

以远程配置为准，远程配置没有，就读本地配置；
是否使用系统变量或者环境变量，这个用户可以通过getProperty函数的第二个参数传入
