### ISSUE TITLE
限流监控有问题

### ISSUE THREAD

**Issue by zxb448126** [polarismesh/polaris-java#358]
**Describe the bug**
我只建了一个限流规则，请求5笔，2笔通过，3笔限流，统计出的指标结果是错乱的：出现两个规则名称、每个规则名称下上报了部分指标

![image](https://user-images.githubusercontent.com/32261659/229448811-34be5d12-ce40-4aec-8798-46865a3b122f.png)

**To Reproduce**
Steps to reproduce the behavior.
sct2020.10.3  
polaris-server v1.16.0

**Expected behavior**
期望将限流指标统计到一个限流规则下

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

**Comment by chuntaojun** [comment]
设置的规则名称是什么？

**Comment by SkyeBeFreeman** [comment]
fixed in Spring Cloud Tencent of version 1.11.1-2020.0.6.
