### ISSUE TITLE
polaris-dependencies 缺少 polaris-all 的依赖

### ISSUE THREAD

**Issue by li-xiao-shuang** [polarismesh/polaris-java#36]
![image](https://user-images.githubusercontent.com/34903552/145704534-21ce0f62-9639-4880-be6a-eaa15226d1c5.png)
polaris-dependencies 缺少 polaris-all 的依赖

**Comment by andrewshan** [comment]
use polaris-all will encounter this error
![image](https://user-images.githubusercontent.com/45474304/146335621-babcad34-b2c7-43ff-b026-d494b9b3e2e0.png)

**Comment by andrewshan** [comment]
it seems that, those revision error, cause by the order of the shade and flatten plugins
https://stackoverflow.com/questions/52552329/use-maven-flatten-plugin-and-maven-shade-plugin-at-the-same-time

**Comment by andrewshan** [comment]
fix it by redefine the flatten plugin in polaris-all
