### ISSUE TITLE
DefaultProviderAPI closed but RegisterFlow's asyncRegisterExecutor don't been closed

### ISSUE THREAD

**Issue by dinstone** [polarismesh/polaris-java#382]
**Describe the bug**

ProviderAPI providerAPI = DiscoveryAPIFactory.createProviderAPIByAddress(clutchOptions.getAddresses());
...
providerAPI.close();

finnally, we closed the providerAPI, but asyncRegisterExecutor is running.

**To Reproduce**
Steps to reproduce the behavior.

InstanceRegisterResponse response = providerAPI.registerInstance(request);
providerAPI.close();

**Expected behavior**

RegisterFlow has close function to been invoke when providerAPI is closing.

**Environment**
- Version: [e.g. v1.12.3]
- OS: [e.g. CentOS8]

**Additional context**

**Comment by SkyeBeFreeman** [comment]
`asyncRegisterExecutor` should be shutdowned when `ProviderAPI` is closed. Are you willing to contribute code to fix this issue?

**Comment by dinstone** [comment]
Maybe I can give it a try.
