### ISSUE TITLE
can polaris-java support shenyu?

### ISSUE THREAD

**Issue by moremind** [polarismesh/polaris-java#396]
ShenYu will support Polaris, but I want to know can polaris java client support reactor?

the pr is:https://github.com/apache/shenyu/pull/4410, but this pr can't pass ci.

if there are some questions, I will contribute for this repository

**Comment by fabian4** [comment]
The pr is still in progress, But I'll finish it soon. 
https://github.com/polarismesh/polaris/issues/1134

I am sorry for the delay in the project.

**Comment by moremind** [comment]
HI，@fabian4 ShenYu will release the 2.6.0 version, can the pull request(https://github.com/apache/shenyu/pull/4410) merge?

**Comment by fabian4** [comment]
> HI，@fabian4 ShenYu will release the 2.6.0 version, can the pull request([apache/shenyu#4410](https://github.com/apache/shenyu/pull/4410)) merge?

Just waiting for https://github.com/polarismesh/polaris-java/pull/404, and then we will release a version. 

I think we can finish it this weekend.

@moremind @chuntaojun

**Comment by fabian4** [comment]
https://github.com/polarismesh/polaris/issues/1134

It's merged now and we can close this issue @chuntaojun

**Comment by moremind** [comment]
@fabian4 Thank you for your contribution and look forward to communicating with you.
