### ISSUE TITLE
监控数据上报需实现定时清理逻辑，防止数据堆积

### ISSUE THREAD

**Issue by SkyeBeFreeman** [polarismesh/polaris-java#528]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

**Comment by chuntaojun** [comment]
应该不止，估计还需要考虑针对 label value 做一些通配，否则上报的数据过大会导致 prometheus 直接无法使用
